"""
Run Streamlit Dashboard - Quick Start

This script provides instructions and examples for running the bibliometric dashboard.

For actual dashboard execution, use:
    streamlit run src/visualization/streamlit_dashboard.py

Author: Bibliometric Analysis System
Date: 2024
"""

import sys
from pathlib import Path

print("=" * 70)
print("BIBLIOMETRIC ANALYSIS DASHBOARD - QUICK START")
print("=" * 70)
print()
print("To run the interactive dashboard, execute the following command:")
print()
print("    streamlit run src/visualization/streamlit_dashboard.py")
print()
print("Or from the project root directory:")
print()
print("    python -m streamlit run src/visualization/streamlit_dashboard.py")
print()
print("=" * 70)
print("FEATURES:")
print("=" * 70)
print()
print("📈 OVERVIEW PAGE")
print("   - Total publications, years covered, unique venues")
print("   - Distribution by publication type")
print("   - Top 10 most productive venues")
print("   - Publication trend over time")
print()
print("🌍 GEOGRAPHIC PAGE")
print("   - Interactive world map with publication distribution")
print("   - Top 10 countries ranking")
print("   - Distribution by continent")
print()
print("☁️ WORD CLOUD PAGE")
print("   - Adjustable number of terms (20-200)")
print("   - Multiple weighting methods (TF-IDF, log, frequency, normalized)")
print("   - Top 20 terms bar chart")
print("   - Searchable term table")
print()
print("📅 TIMELINE PAGE")
print("   - Interactive charts (Line, Area, Bar)")
print("   - Yearly statistics with growth rates")
print("   - Future projections based on linear regression")
print("   - Downloadable CSV data")
print()
print("📄 EXPORT PDF PAGE")
print("   - Professional PDF report generation")
print("   - Configurable sections")
print("   - High-quality images (300 DPI)")
print("   - Direct download")
print()
print("=" * 70)
print("FILTERS:")
print("=" * 70)
print()
print("All pages support real-time filtering:")
print("   - Year range slider")
print("   - Venue selection (multiselect)")
print("   - Publication type selection (multiselect)")
print()
print("=" * 70)
print("DATA REQUIREMENTS:")
print("=" * 70)
print()
print("The dashboard expects a CSV file with the following columns:")
print()
print("Required columns:")
print("   - id: Unique identifier")
print("   - title: Publication title")
print("   - authors: Authors with affiliations in parentheses")
print("   - year: Publication year")
print("   - abstract: Abstract text")
print("   - keywords: Keywords (semicolon-separated)")
print("   - journal_conference: Venue name")
print("   - publication_type: 'journal' or 'conference'")
print()
print("Example CSV format:")
print()
print("id,title,authors,year,abstract,keywords,journal_conference,publication_type")
print('pub_001,"AI Research","John Doe (MIT, USA)",2023,"This study...","AI; ML",IEEE Trans,journal')
print()
print("=" * 70)
print("DEFAULT DATA PATH:")
print("=" * 70)
print()
print("Default: data/sample/complete_sample_data.csv")
print()
print("To use custom data:")
print("1. Edit src/visualization/streamlit_dashboard.py")
print("2. Change the 'default_path' variable (line ~736)")
print("3. Save and run the dashboard")
print()
print("=" * 70)
print("SAMPLE DATA GENERATION:")
print("=" * 70)
print()
print("To generate sample data, run:")
print()
print("    python examples/complete_visualization_demo.py")
print()
print("This will create sample data at: data/sample/complete_sample_data.csv")
print()
print("=" * 70)
print("DEPENDENCIES:")
print("=" * 70)
print()
print("Ensure all dependencies are installed:")
print()
print("    pip install -r requirements.txt")
print()
print("Key dependencies:")
print("   - streamlit>=1.28.0")
print("   - pandas>=1.3.0")
print("   - plotly>=5.14.0")
print("   - reportlab>=4.0.0 (for PDF export)")
print()
print("=" * 70)
print("TROUBLESHOOTING:")
print("=" * 70)
print()
print("Issue: Data file not found")
print("Solution: Generate sample data or provide custom CSV path")
print()
print("Issue: Import errors")
print("Solution: Install dependencies with 'pip install -r requirements.txt'")
print()
print("Issue: Dashboard won't start")
print("Solution: Ensure Streamlit is installed: 'pip install streamlit'")
print()
print("Issue: Visualizations not showing")
print("Solution: Check data format and required columns")
print()
print("=" * 70)
print("PERFORMANCE TIPS:")
print("=" * 70)
print()
print("- Use the 'Refresh Data' button to clear cache")
print("- Adjust year range to reduce dataset size")
print("- Select specific venues for focused analysis")
print("- Large datasets may take longer to generate PDFs")
print()
print("=" * 70)
print("EXAMPLE WORKFLOW:")
print("=" * 70)
print()
print("1. Generate sample data:")
print("   python examples/complete_visualization_demo.py")
print()
print("2. Start dashboard:")
print("   streamlit run src/visualization/streamlit_dashboard.py")
print()
print("3. Explore in browser:")
print("   - Navigate to http://localhost:8501")
print("   - Use sidebar to select pages")
print("   - Apply filters as needed")
print()
print("4. Export report:")
print("   - Go to 'Export PDF' page")
print("   - Configure report settings")
print("   - Click 'Generate PDF Report'")
print("   - Download the report")
print()
print("=" * 70)
print("READY TO START!")
print("=" * 70)
print()
print("Execute the command below to launch the dashboard:")
print()
print("    streamlit run src/visualization/streamlit_dashboard.py")
print()
print("=" * 70)


# Optional: Check if sample data exists
data_path = Path('data/sample/complete_sample_data.csv')
if data_path.exists():
    print()
    print("✅ Sample data found at:", data_path)
    print("   You can start the dashboard immediately!")
    print()
else:
    print()
    print("⚠️  Sample data not found at:", data_path)
    print("   Run 'python examples/complete_visualization_demo.py' to generate it.")
    print()

print("=" * 70)
